apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    for: votingapp-viadeployments

spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        for: votingapp-viapods

    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      for: votingapp-viapods


