apiVersion: apps/v1

kind: Deployment

metadata:
  name: votingapp-deployment
  labels:
    name: votingapp-deployment
    for: votingapp-viadeployments

spec:
  template:
    metadata:
      name: votingapp-pod
      labels:
        name: votingapp-pod
        for: votingapp-viapods

    spec:
      containers:
        - name: votingapp-image
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      name: votingapp-pod
      for: votingapp-viapods

